---
- name: Install rustup
  homebrew:
    name: rustup
    state: present
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  tags:
    - homebrew
    - rust

- name: Check current rustup default toolchain
  command:
    cmd: rustup default
  register: rustup_default
  changed_when: false
  failed_when: false
  environment:
    PATH: "/opt/homebrew/opt/rustup/bin:{{ ansible_env.PATH }}"
  tags:
    - rust

- name: Set rustup default toolchain to stable
  command:
    cmd: rustup default stable
  when: rustup_default.rc != 0 or "'stable' not in rustup_default.stdout"
  environment:
    PATH: "/opt/homebrew/opt/rustup/bin:{{ ansible_env.PATH }}"
  tags:
    - rust

- name: Ensure fish conf.d directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/fish/conf.d"
    state: directory
    mode: "0755"
  tags:
    - rust
    - fishshell

- name: Add rustup path to fish configuration
  copy:
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/rustup.fish"
    content: |
      fish_add_path /opt/homebrew/opt/rustup/bin
    mode: "0644"
  tags:
    - rust
    - fishshell
