---
- hosts: all

  vars:
    # For all homebrew related tasks,
    # remember to add the `become` and `become_user` properties.
    # So that this playbook can be used on a multiple users system.

    homebrew_user: "{{ ansible_user_id }}"
    homebrew_group: admin

    ssh_type: ed25519
    ssh_rounds: 256
    ssh_private_key_path: "~/.ssh/id_{{ ssh_type }}"

  roles:
    - role: preflight

    - role: dotfiles
      tags: [dotfiles]

    - role: ssh
      tags: [ssh]

    - role: homebrew_base
      tags: [homebrew, homebrew-setup]

    - role: dev_tools
      tags: [homebrew]

    - role: casks
      tags: [homebrew]

    - role: shared_fonts
      vars:
        fonts:
          - font-inconsolata-g-for-powerline
          - font-source-code-pro
          - font-source-code-pro-for-powerline

    - role: emacs
      tags: [spacemacs]

    - role: vim
      tags: [vim]

    - role: python_env
      tags: [python]

    - role: shell_fish
      tags: [fishshell]

    - role: fzf
      tags: [fzf]

    - role: folders
      tags: [folder-structure]

    - role: macos_finder
      tags: [finder]

    - role: macos_stage_manager
      tags: [stage-manager]

    - role: macos_dock
      tags: [dock]
